[package]
name = "arduino-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
chrono = "0.4.41"
rumqttc = "0.24.0"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread", "sync"] }
rand = "0.9.1"
